name: Threatlens CI/CD workflow

on:
    push:
        branches: 
            - main
        paths-ignore:
            - README.md

jobs: 
    integration:
        name: Continuous Integration
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Lint code
              uses: echo "Linting code..."
            
            - name: Run unit tests
              uses: echo "Running unit tests..."